# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'list'
  page: 'setting'
  tasks:
    Alas:
      - Emulator
      - EmulatorInfo
      - Error
      - Optimization
    Restart:
      - Scheduler

# ==================== Daily ====================

Daily:
  menu: 'list'
  page: 'setting'
  tasks:
    DailyQuest:
      - Scheduler
      - DailyQuestOptions
      - DailyStorage


    Dungeon:
      - Scheduler
      - Dungeon

    MealPower:
      - Scheduler
      - MealPower

    Guild:
      - Scheduler
      - GuildMission
      - GuildActivity
      - Cosplay


    Shop:
      - Scheduler
      - MonthlyCard

    BattlePass:
      - Scheduler
      - BattlePassStorage

    DataUpdate:
      - Scheduler
      - ItemStorage



  # ==========================Tool====================

Tool:
  menu: 'list'
  page: 'tool'
  tasks:
    ClearJinGeTalisman:
      - ClearJinGeTalisman
      - JinGeStorage


    # DailyPassword:
    #   - DailyPassword
